name: Build, Test, Release, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build with webpack
      run: npm run build

    - name: Run tests
      run: npm test
      # Add your test command here

  #release:
  #  runs-on: ubuntu-latest
  #  needs: build
  #
  #  steps:
  #  - name: Create Release
  #    id: create_release
  #    uses: actions/create-release@v1
  #    env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #    with:
  #      tag_name: v1.0.0  # Replace with your desired tag name
  #      release_name: Release 1.0.0  # Replace with your desired release name
  #      draft: false
  #      prerelease: false

  #deploy:
  #  runs-on: ubuntu-latest
  #  needs: [build, release]
#
  #  steps:
  #  - name: Deploy to jsdelivr
  #    uses: jsdelivr/action@v1
  #    with:
  #      args: "dist/index.js"
  #      zone_id: ${{ secrets.JSDLIVER_ZONE_ID }}
  #      access_token: ${{ secrets.JSDLEIVER_ACCESS_TOKEN }}

  badges:
    runs-on: ubuntu-latest

    steps:
    - name: Add test badge to README
      run: echo "![Tests](https://img.shields.io/github/workflow/status/bradhuang9999/TourGroup.js/Build,%20Test,%20Release,%20and%20Deploy/main?label=Tests)" >> README.md
      # Replace YourUsername and YourRepositoryName with your GitHub username and repository name